# Generated by Django 5.2.7 on 2025-10-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_content', '0001_initial'),
        ('quizzes', '0003_quiz_passing_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcontent',
            name='quiz_details',
        ),
        migrations.AddField(
            model_name='quizcontent',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_content_quizzes', to='quizzes.quiz'),
            preserve_default=False,
        ),
    ]
