# Generated by Django 6.0.3 on 2026-03-18 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0016_course_code_alter_course_title'),
        ('lesson_content', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcontent',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_content_quizzes', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_contents', to='courses.lesson'),
        ),
    ]
