# Generated by Django 6.0.3 on 2026-04-17 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_lesson_coding_instructions_lesson_coding_language_and_more'),
        ('lesson_content', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcontent',
            name='module',
        ),
        migrations.AddField(
            model_name='quizcontent',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_contents', to='courses.lesson'),
        ),
    ]
