# Generated by Django 4.2.7 on 2025-10-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_rename_certificate_id_certificate_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
