# Generated by Django 4.2.7 on 2025-10-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learning_preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
