# Generated by Django 6.0.3 on 2026-03-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_address_user_bio_user_daily_study_goal_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS accounts_instructorrequest;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
