# Generated by Django 5.2.7 on 2025-10-15 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criteriarating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='criteriarating',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='criteriarating',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='review',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='review',
            name='helpful_votes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_verified_purchase',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reported_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='unhelpful_votes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='would_recommend',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReviewCriteria',
        ),
        migrations.DeleteModel(
            name='CriteriaRating',
        ),
        migrations.DeleteModel(
            name='ReviewResponse',
        ),
    ]
