# Generated by Django 5.2.7 on 2025-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_files',
            field=models.FileField(blank=True, null=True, upload_to='lesson_attachments/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
