# Generated by Django 4.2.7 on 2025-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lesson_lesson_files_lesson_text_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_files',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='text_content',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to a video (e.g., YouTube, Vimeo)', null=True),
        ),
    ]
