# Generated by Django 6.0.3 on 2026-04-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_course_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='coding_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='coding_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='has_coding_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stdin_placeholder',
            field=models.TextField(blank=True),
        ),
    ]
