# Generated by Django 5.2.7 on 2025-10-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lesson_lesson_files_lesson_text_content_and_more'),
        ('quizzes', '0003_quiz_passing_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson'),
            preserve_default=False,
        ),
    ]
